version: '2.1'
services:
  postgres:
    image: postgres:10.4
    container_name: postgres
    environment:
      - POSTGRES_USER=sonar 
      - POSTGRES_PASSWORD=sonar 
      - POSTGRE_DB=sonar
    volumes:
      - /data/postgresql:/var/lib/postgresql/data
    network_mode: host
    restart: always
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://127.0.0.1:5432/sonar
    volumes:
      - /data/sonarqube/conf:/opt/sonarqube/conf
      - /data/sonarqube/data:/opt/sonarqube/data
      - /data/sonarqube/extensions:/opt/sonarqube/extensions
      - /data/sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    network_mode: host
    restart: always