version: '2.1'
services:
  postgresql:
    image: bitnami/postgresql:9.6
    volumes:
      - /data/postgresql:/bitnami
    network_mode: host
    restart: always
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /data/redis:/bitnami
    network_mode: host
    restart: always
  discourse:
    image: bitnami/discourse:latest
    volumes:
      - /data/discourse:/bitnami
    environment:
      - POSTGRESQL_HOST=127.0.0.1
      - REDIS_HOST=127.0.0.1
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_application
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_discourse
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - SMTP_HOST=smtp.ym.163.com
      - SMTP_PORT=465
      - SMTP_USER=info@install.dog
      - SMTP_PASSWORD=Iechaht3mohsh9wohr7Jue2Ohboo3iet
    network_mode: host
    restart: always
  sidekiq:
    image: 'bitnami/discourse:latest'
    volumes:
      - /data/sidekiq:/bitnami
    command: 'nami start --foreground discourse-sidekiq'
    environment:
      - DISCOURSE_POSTGRESQL_NAME=bitnami_application
      - DISCOURSE_POSTGRESQL_USERNAME=bn_discourse
      - DISCOURSE_POSTGRESQL_PASSWORD=bitnami1
      - DISCOURSE_HOST=127.0.0.1
      - DISCOURSE_PORT=3000
      - SMTP_HOST=smtp.ym.163.com
      - SMTP_PORT=465
      - SMTP_USER=info@install.dog
      - SMTP_PASSWORD=Iechaht3mohsh9wohr7Jue2Ohboo3iet
    network_mode: host
    restart: always
